name: tests
on:
  pull_request:
  push:
    branches: [ main ]

  schedule:
  - cron: '25 08 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

defaults:
  run:
    shell: bash

jobs:
  tests:
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        ddev_version: [stable, HEAD]
#        ddev_version: [stable, edge, HEAD, PR]
      fail-fast: false

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install DDEV
      uses: mxr576/github-action-setup-ddev@install-ddev-as-binary-without-retry
  
    - name: Download docker images
      run: mkdir junk && pushd junk && ddev config --auto && ddev debug download-images >/dev/null

    - name: tmate debugging session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
      if: github.event.inputs.debug_enabled == 'true'

    - name: tests
      run: ./tests/bats/bin/bats -t tests
